mod error;
pub use error::{MicrocodeError, Result};

pub use crate::cpu_instruction::{CPUInstruction, LogLine};
pub use crate::registers::Registers;
pub use crate::memory::MemoryStack as Memory;
pub use crate::memory::AddressableIO;
pub use crate::addressing_mode::*;
pub use super::STACK_BASE_ADDR;

mod dex;
mod dey;
mod pha;
mod lda;
mod ldx;
mod ldy;
mod sta;
mod stz;
mod jmp;
mod eor;
mod stx;
mod adc;
mod sbc;
mod bne;
mod beq;
mod bra;
mod brk;
mod tax;
mod inx;
mod iny;
mod ina;
mod nop;

pub use dex::dex;
pub use dey::dey;
pub use pha::pha;
pub use lda::lda;
pub use ldy::ldy;
pub use ldx::ldx;
pub use sta::sta;
pub use stz::stz;
pub use jmp::jmp;
pub use eor::eor;
pub use stx::stx;
pub use adc::adc;
pub use sbc::sbc;
pub use bne::bne;
pub use beq::beq;
pub use bra::bra;
pub use brk::brk;
pub use tax::tax;
pub use inx::inx;
pub use iny::iny;
pub use ina::ina;
pub use nop::nop;
