[package]
name = "soft65c02_lib"
version = "1.0.0-alpha2"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
range-map   = "0.1.5"
minifb      = "0.15.1"
hex         = "0.4.0"
rand        = "0.7.3"
